server:
 port: 8083
spring:
 application:
   name: limite
 data:
   mongodb:
     uri: ${mongo_url:mongodb://localhost:27017/workshop-springboot-limite}
 cloud:
   consul:
     host: localhost
     port: 8500
     config:
       enabled: true
       prefix: config
       defaultContext: apps
       profileSeparator: '::'
   stream:
     bindings:
       contaCorrenteCriada:
         destination: conta-corrente-criada
         group: conta-corrente-criada-group
     binders:
       rabbitMQ:
         type: rabbit
         environment:
           spring:
             rabbitmq:
               addresses: ${rabbit.addresses:localhost:5672}
               username: ${rabbit.username:guest}
               password: ${rabbit.password:guest}
               virtual-host: ${rabbit.virtualhost:/}
logging:
 level:
   root: ${logging_level:INFO}
service:
 spring-boot-demo:
   url: http://localhost:9090/api/spring-boot-demo/cpf/{cpf}
limite:
  credito: 1000